/*
 * DEVELOPMENT TOOL. Not part of piHPSDR - see README.md.
 *
 * Replays a .divc capture into the RADE V1 pilot correlator, and sweeps
 * the correlator's constants against it.
 *
 * The point of the exercise: every number in rade_correlator.c was set
 * against a synthetic signal generated by test_rade.c. This runs the same
 * code against a recording of a real one, as many times as a sweep needs,
 * deterministically.
 *
 * Replay is at the block level, calling rade_corr_process() directly with
 * the bank, frame offset, averaging time and hang the live run used. That
 * is why the capture is taken at block granularity: there is no queue, no
 * worker thread and no g_usleep() pacing to get wrong, and no way for the
 * harness to drop a block and quietly re-acquire the way feeding samples
 * through diversity_auto_sample() too fast does.
 *
 *   replay_rade cap.divc --verify
 *   replay_rade cap.divc --set use_ratio=2.0 --set probation=4
 *   replay_rade cap.divc --sweep use_ratio=1.5:4.0:0.25 --csv out.csv
 *
 * --verify first, always. It checks that the replayed correlator state
 * matches what the radio recorded block by block. Until that passes, a
 * sweep is measuring the harness rather than the correlator.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdarg.h>
#include <gtk/gtk.h>

#include "mode.h"
#include "receiver.h"
#include "vfo.h"
#include "diversity_auto.h"
#include "rade_correlator.h"
#include "rade_tuning.h"
#include "diversity_capture.h"
#include "divcap_replay.h"

/*
 * Stubs, as in the rest of test/diversity: the real RECEIVER and vfo
 * types, because a stub struct reads the wrong offsets.
 */
static RECEIVER rx0;
RECEIVER *receiver[8] = { &rx0 };
int receivers = 2;
int diversity_enabled = 1;
int radio_is_remote = 0;
int cw_keyer_sidetone_frequency = 800;
double div_cos = 1.0, div_sin = 0.0, div_gain = 0.0, div_phase = 0.0;
struct _vfo vfo[MAX_VFOS];

static int verbose = 0;
void t_print(const char *fmt, ...) {
  if (!verbose) { return; }

  va_list a;
  va_start(a, fmt);
  vprintf(fmt, a);
  va_end(a);
}
const char *getProperty(const char *n) { (void)n; return NULL; }
void setProperty(const char *n, const char *v) { (void)n; (void)v; }
double myatof(const char *s) { return atof(s); }

/* ------------------------------------------------------------------ */

#define MAX_SWEEP 3
#define MAX_SET   16

struct sweep_axis {
  const char *name;
  double lo, hi, step;
  int    n;
};

struct setting {
  const char *name;
  double value;
};

static void usage(const char *me) {
  fprintf(stderr,
          "usage: %s FILE.divc [--verify] [--from N] [--set name=v]... \n"
          "       [--sweep name=lo:hi:step]... [--csv OUT] [--weights OUT]\n"
          "       [--tau S] [--hang S] [--noise RMS] [--seed N] [-v]\n\n"
          "--tau/--hang override the operator settings the capture recorded.\n"
          "--noise adds independent AWGN of that rms to each arm, per component,\n"
          "which is the one part of the noise a two-branch array cannot null.\n"
          "--weights writes the correlator's weight for every block.\n"
          "--from ignores verify mismatches before block N, for a capture that\n"
          "was already locked when it started.\n\n"
          "settable names:\n  ", me);

  for (int i = 0; rade_tuning_name(i) != NULL; i++) {
    fprintf(stderr, "%s%s", (i > 0) ? ", " : "", rade_tuning_name(i));
  }

  fprintf(stderr, "\n");
}

int main(int argc, char **argv) {
  const char *path = NULL;
  const char *csv  = NULL;
  const char *wpath = NULL;
  int verify = 0;
  struct sweep_axis axis[MAX_SWEEP];
  struct setting    set[MAX_SET];
  int naxis = 0, nset = 0;
  struct divcap_opts opts;
  memset(&opts, 0, sizeof(opts));

  for (int i = 1; i < argc; i++) {
    if (!strcmp(argv[i], "-v")) {
      verbose = 1;
    } else if (!strcmp(argv[i], "--verify")) {
      verify = 1;
    } else if (!strcmp(argv[i], "--csv") && i + 1 < argc) {
      csv = argv[++i];
    } else if (!strcmp(argv[i], "--weights") && i + 1 < argc) {
      wpath = argv[++i];
    } else if (!strcmp(argv[i], "--tau") && i + 1 < argc) {
      opts.tau = atof(argv[++i]);
    } else if (!strcmp(argv[i], "--hang") && i + 1 < argc) {
      opts.hang = atof(argv[++i]);
    } else if (!strcmp(argv[i], "--noise") && i + 1 < argc) {
      opts.noise = atof(argv[++i]);
    } else if (!strcmp(argv[i], "--seed") && i + 1 < argc) {
      opts.seed = (unsigned)atoi(argv[++i]);
    } else if (!strcmp(argv[i], "--from") && i + 1 < argc) {
      opts.from_block = atoi(argv[++i]);
    } else if (!strcmp(argv[i], "--set") && i + 1 < argc) {
      char *s = argv[++i];
      char *eq = strchr(s, '=');

      if (eq == NULL || nset >= MAX_SET) { usage(argv[0]); return 2; }

      *eq = '\0';
      set[nset].name  = s;
      set[nset].value = atof(eq + 1);

      if (!rade_tuning_set(set[nset].name, set[nset].value)) {
        fprintf(stderr, "replay: unknown setting \"%s\"\n", set[nset].name);
        usage(argv[0]);
        return 2;
      }

      nset++;
    } else if (!strcmp(argv[i], "--sweep") && i + 1 < argc) {
      char *s = argv[++i];
      char *eq = strchr(s, '=');

      if (eq == NULL || naxis >= MAX_SWEEP) { usage(argv[0]); return 2; }

      *eq = '\0';

      if (!rade_tuning_set(s, 0.0)) {
        fprintf(stderr, "replay: unknown setting \"%s\"\n", s);
        usage(argv[0]);
        return 2;
      }

      if (sscanf(eq + 1, "%lf:%lf:%lf",
                 &axis[naxis].lo, &axis[naxis].hi, &axis[naxis].step) != 3
          || axis[naxis].step <= 0.0) {
        fprintf(stderr, "replay: --sweep wants name=lo:hi:step\n");
        return 2;
      }

      axis[naxis].name = s;
      axis[naxis].n = (int)floor((axis[naxis].hi - axis[naxis].lo) / axis[naxis].step + 1.0e-9) + 1;

      if (axis[naxis].n < 1) { axis[naxis].n = 1; }

      naxis++;
    } else if (argv[i][0] == '-') {
      usage(argv[0]);
      return 2;
    } else if (path == NULL) {
      path = argv[i];
    } else {
      usage(argv[0]);
      return 2;
    }
  }

  if (path == NULL) { usage(argv[0]); return 2; }

  opts.verify = verify;
  struct divcap_header h;
  long data_start = 0;
  FILE *f = divcap_open(path, &h, &data_start);

  if (f == NULL) { return 1; }

  printf("# %s\n", path);
  printf("# radio      %s\n", h.radio);
  printf("# note       %s\n", h.note);
  printf("# rate       %u Hz, nfft %u (%.1f ms/block)\n",
         h.sample_rate, h.nfft, 1000.0 * (double)h.nfft / (double)h.sample_rate);

  FILE *out = stdout;

  if (csv != NULL) {
    out = fopen(csv, "w");

    if (out == NULL) { perror(csv); fclose(f); return 1; }
  }

  /* Header row: the swept names, then the metrics. */
  for (int a = 0; a < naxis; a++) { fprintf(out, "%s,", axis[a].name); }

  fprintf(out, "blocks,seconds,acquisitions,locked_frac,first_lock_s,"
          "mean_snr_db,mean_quality,weight_jitter");

  if (verify) { fprintf(out, ",verify_checked,verify_bad"); }

  fprintf(out, "\n");

  /* Nested sweep. With no axes this runs exactly once. */
  int idx[MAX_SWEEP] = { 0, 0, 0 };
  int total = 1;

  for (int a = 0; a < naxis; a++) { total *= axis[a].n; }

  int failures = 0;

  for (int point = 0; point < total; point++) {
    int rest = point;

    for (int a = naxis - 1; a >= 0; a--) {
      idx[a] = rest % axis[a].n;
      rest /= axis[a].n;
    }

    /*
     * Start from the shipped values every time, then re-apply the --set
     * overrides, then the sweep point. One point can therefore never
     * inherit anything from another.
     */
    rade_tuning_defaults();

    for (int s = 0; s < nset; s++) { rade_tuning_set(set[s].name, set[s].value); }

    for (int a = 0; a < naxis; a++) {
      rade_tuning_set(axis[a].name, axis[a].lo + idx[a] * axis[a].step);
    }

    struct divcap_result r;

    /*
     * One weight file per run, so a sweep does not interleave points.
     * With more than one point the axis values go in the name.
     */
    if (wpath != NULL) {
      char name[512];

      if (total > 1) {
        char sfx[256];
        int used = 0;

        for (int a = 0; a < naxis; a++) {
          used += snprintf(sfx + used, sizeof(sfx) - used, "-%s%g",
                           axis[a].name, rade_tuning_get(axis[a].name));
        }

        snprintf(name, sizeof(name), "%s%s", wpath, sfx);
      } else {
        snprintf(name, sizeof(name), "%s", wpath);
      }

      opts.weights = fopen(name, "w");

      if (opts.weights == NULL) { perror(name); fclose(f); return 1; }
    }

    if (!divcap_replay(f, &h, data_start, &opts, &r)) { fclose(f); return 1; }

    if (opts.weights != NULL) { fclose(opts.weights); opts.weights = NULL; }

    for (int a = 0; a < naxis; a++) {
      fprintf(out, "%g,", rade_tuning_get(axis[a].name));
    }

    fprintf(out, "%d,%.2f,%d,%.4f,%.2f,%.2f,%.4f,%.5f",
            r.blocks, r.seconds, r.acquisitions,
            (r.blocks > 0) ? (double)r.locked_blocks / r.blocks : 0.0,
            r.first_lock, r.mean_snr, r.mean_quality, r.weight_jitter);

    if (verify) { fprintf(out, ",%d,%d", r.verify_checked, r.verify_bad); }

    fprintf(out, "\n");
    fflush(out);
    failures += r.verify_bad;
  }

  if (csv != NULL) {
    fclose(out);
    printf("# %d point(s) written to %s\n", total, csv);
  }

  fclose(f);

  if (verify) {
    if (failures == 0) {
      printf("# verify: replay reproduces the recorded run\n");
    } else {
      printf("# verify: %d block(s) differ - do NOT trust a sweep over this capture\n",
             failures);
    }

    return (failures == 0) ? 0 : 1;
  }

  return 0;
}
